### ISSUE TITLE
Permission commands are still not properly working

### ISSUE THREAD

**Issue by Inrixia** [Inrixia/serverWrapper.ts#20]
Use `~cwSet * @User` for testing

**Comment by greysilly7** [comment]
Correct way is `~swset @User *`

**Comment by Inrixia** [comment]
The example args need to be updated to reflect the proper order then. 
![Screenshot_20220806-100212_Discord](https://user-images.githubusercontent.com/6373693/183217327-a19db9e2-d7c8-4988-a068-8a481ed84d3c.png)

**Comment by greysilly7** [comment]
Kek I'll fix it in a bit
